### ISSUE TITLE
Output a list of all the jubilee line stations to the console

### ISSUE THREAD

**Issue by gozumi** [gozumi/london-tube-live#3]
This output should appear in the correct sequence order.

### TODOs
- [x] Find the correct tfl api URL that will give you all the stations on a given line.
- [ ] Initialise the app with a call to that URL.
- [ ] Output the station list to the console.

**Comment by gozumi** [comment]
### Order sequence of line stops
The ordered stop sequences for inbound and outbound routes can be requested from the following URL's
- https://api.tfl.gov.uk/Line/<line id>/Route/Sequence/inbound
  - example - https://api.tfl.gov.uk/Line/jubilee/Route/Sequence/inbound
- https://api.tfl.gov.uk/Line/<line id>/Route/Sequence/outbound
  - example - https://api.tfl.gov.uk/Line/jubilee/Route/Sequence/outbound
